### ISSUE TITLE
Can't update to 1.2.8

### ISSUE THREAD

**Issue by CodyMKW** [SethClydesdale/forumactif-edge#42]
I saw there was a new update but when I clicked the check for updates button in the control panel it just displays "Checking for updates on Github..." but doesn't do anything
![2018-06-06_11-16-17](https://user-images.githubusercontent.com/8176523/41047817-634ed964-697b-11e8-9e39-55bc34d1433b.gif)

**Comment by CodyMKW** [comment]
Nevermind found the issue for some reason "Enable Javascript code management" was turned off in admin panel sorry

**Comment by SethClydesdale** [comment]
Thanks for posting the solution ! 👍  

I assumed it could've been that, because Forumotion disabled JavaScript codes management on all of the forums quite recently. If you manage any other forums on the service, I'd check them to make sure it's enabled.

Still, I'm going to review the control panel to ensure that it can function with JS Codes management disabled, because it's definitely a minor bug. Thanks for bringing it to my attention.

EDIT:
It should be fixed now. When JS Codes Management is disabled it should display an error with a prompt that asks to check if it's enabled along with the standard "open a new issue" in the event JS codes management IS enabled.
