### ISSUE TITLE
Font Awesome 5.10

### ISSUE THREAD

**Issue by ghost** [SethClydesdale/forumactif-edge#47]
Hello,

How to migrate for Font Awesome 4.7 to 5.10 ?

Thanks in advance Seth and sorry for the question  !

**Comment by SethClydesdale** [comment]
Hello,

Font Awesome has a topic on how to migrate [here](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4). You'll have to update the CDN in the CSS style sheet too: 
```css
@import url(https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css);
```

However, it requires quite a bit of work, because the prefixes for some icons changed, so migrating to 5 will cause those icons not to work unless they're properly changed. This is the reason I never upgraded to v5 for Forumactif Edge, because I'd risk possibly breaking the features of users forums.

**Comment by ghost** [comment]
Oh I see, "dommage"

Thanks for the answer
